language: r
warnings_are_errors: false
sudo: required

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libxml2-dev
      - libgit2-dev
      - libssl-dev
      - libssh2-1-dev
      - pandoc
      - pandoc-citeproc
      - r-cran-testthat
      - r-cran-devtools
      - r-cran-tidyverse
      - r-cran-rcppeigen
      - r-cran-bh

install:
  - R -e 'install.packages("devtools"); devtools::install_deps(dep = T)'

script:
  - R CMD build .
  - R CMD check *.tar.gz
  - R CMD INSTALL *.tar.gz
  - R -e 'library(fluEvidenceSynthesis);library(rmarkdown);render("vignettes/modelling.Rmd");render("vignettes/inference.Rmd");render("vignettes/vaccination.Rmd");render("vignettes/adapting-the-transmission-model.Rmd");'

os:
- linux
- osx

notifications:
  slack: phe-flumod:lk26uoOoSWKaKpmJiHSesYNW

after_success: ./travis.sh

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = "linux"
